#+TITLE: Jordan Herzstein
#+INCLUDE: "~/Website/content/base.org::*Header" :only-contents t
#+OPTIONS: toc:nil
* Personal Computer / Hardware
I currently mainly use a librebooted ThinkPad T400, specially modded with a quad core CPU. It runs Debian 11 as the base operating system, and I have the non-free and contrib repositories disabled such that I can avoid non-free software on my machine. I also have a ThinkPad P15s that dual boots Arch Linux and Windows 10. I generally use this machine a lot less due to freedom issues with Windows and to a lesser extent Arch, but still sees some use for when I need a virtual machine for malware such as proctortrack.

* Software
In terms of software, Emacs is a huge part of my productivity environment, and acts as my IDE, document writer, RSS feed, and I even made this site with it! I of course use evil mode due to the extramarital affair I have with Vim. Outside of Emacs I use dwm, which is the only real window manager I've used, though I may switch if there's an equally viable alternative for wayland or if I'm curious enough to try EXWM. My shell is bash, never really botherd to use anything else really. For browsing I use Librewolf, a fork of Firefox with more privacy protections by default, with ublock origin and librejs. 

#+INCLUDE: "~/Website/content/base.org::*Footer" :only-contents t
