#+TITLE: Jordan Herzstein
#+INCLUDE: "~/Website/content/base.org::*Header" :only-contents t
#+OPTIONS: toc:nil

* VPC Setup
I'm currently using a ROCKpro64 with it's respective NAS case and PCI-e SSD interface card. It runs DietPi, which is a distrobution of Debian optimized for arm SBCs. 

I also have a lynksys router at home that I use to run openwrt for it's security, performance, and customizability, especially compared to the default modems provided by ISPs.
# I've been experiementing with running port 80 and 443 traffic through a Wireguard vpn to bypass those pesky ISPs (learn how to do that [[https://wickedyoda.com/using-wireguard-and-a-vps-to-bypass-isp-port-blocking-and-hide-your-public-ip/][here]] and [[https://www.reddit.com/r/selfhosted/comments/kphfd3/nginx_reverse_proxy_via_vpn/][here]]).

* Personal Computer / Hardware
Right now I'm mosting using a Thinkpad T430 running Qubes OS with an i7-3840QM and 16GB of RAM that I corebooted myself. Last year I was daily-driving a [[https://libreboot.org/][librebooted]] ThinkPad T400, [[https://vid.puffyan.us/watch?v=Fs4GjDiOie8][specially modded]] with a quad core CPU. It runs Debian 12, and I'm guessing the only non-free software running on it is the trackpad firmware. I also have a ThinkPad P15s that dual boots Arch Linux and Windows 10. I generally use this machine a lot less because the keyboard and mouse are broken and I haven't bothered to get it fixed for the past year and a half. I like listening to music while I study or run, for that I use an ipod nano 2g with [[https://www.rockbox.org/][RockBox]], a free firmware replacement for music players that can also play Doom. Recently I've been loading a lot of books, manga, and even school materials onto my Kobo Libra 2 (which I keep offline). It's has been really nice on my eyes, maybe I'll get around to trying the [[https://www.pine64.org/pinenote/][PineNote]] for it's full consumer release.

* Cell Phone
I own an unlocked Pixel 7 running [[https://grapheneos.org][GrapheneOS]]. Yes, I do enjoy the premium degoogled android experience on Google's very own hardware. Regardless, the stuff that the GrapheneOS team are doing is very impressive, if you're interested in using it make sure you purchase a compatable pixel device that is *unlocked*.

* Software
In terms of software, Emacs is a huge part of my productivity environment, and acts as my IDE, document writer, RSS feed, and I even made this site with it! I of course use evil mode due to the extramarital affair I have with Vim. I've used a couple of window managers including dwm and awesomewm, but I'm sure I'll get to using wayland one of these years. My shell is bash, never really bothered to use anything else really. For browsing I use Librewolf, a fork of Firefox with more privacy protections by default. 
#+INCLUDE: "~/Website/content/base.org::*Footer" :only-contents t
