#+TITLE: Welcome to YortNet
#+date: 2024-07-26
#+hugo_base_dir: ../../
#+HUGO_AUTO_SET_LASTMOD: t
#+hugo_section: posts
#+HUGO_MENU: :menu "posts"
#+filetags: vps technology oracle updates
#+HUGO_CODE_FENCE: 
#+EXPORT_FILE_NAME: welcome_to_yortnet.md
#+hugo_front_matter_key_replace: description>summary
#+begin_description
I spun up a vps to host various services and privacy front ends
#+end_description

I created the website [[https://yortnet.com][yortnet.com]] on the same oracle vps which I set up my free minecraft server through docker to also host various services and privacy front ends. I personally always use open source privacy front ends for accessing various internet resources, and I figured I might as well put some of my skills to use to provide some value as it would only cost me around $10 a year to renew the domain. Right now I just have a [[https://searx.yortnet.com][searx]] instance (a metasearch engine) running on the server though I plan on adding more services in the future when I have the free time. Everything runs behind an NGINX reverse proxy in which I have partially anonymized the logs which do not leave the server; see the privacy policy for more details. I hope you enjoy.


