#+TITLE: My Setup
#+AUTHOR: Jordan Herzstein 
#+DATE: 2024-02-06
#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: mysetup
#+HUGO_MENU: :menu "mysetup"
#+HUGO_CODE_FENCE: nil
#+EXPORT_FILE_NAME: _index.md

* This Site
This is my personal website which I've been hosting on neocities since late 2022. Since +January 2024+ May 2024, I now host at +jordanherzstein.xyz+ [[http://jordanherzstein.com][jordanherzstein.com]] on github pages, which is a temporary stopgap for hosting services publicly in the future, whenever I'm not, uhh.. busy, while still being able to have my custom domain without paying anything extra to those hosting me. The site itself is made with [[https://orgmode.org/][Org Mode]] using [[https://gohugo.io/][Hugo]] (static site generator) and [[https://ox-hugo.scripter.co/][ox-hugo]] (an Org exporter to Markdown for Hugo on Emacs).

* VPC 
I'm currently using a ROCKpro64 with it's respective NAS case and PCI-e SSD interface card. It runs DietPi, which is a distrobution of Debian optimized for arm SBCs. 

I also have a lynksys router at home that I use to run openwrt for it's security, performance, and customizability, especially compared to the default modems provided by ISPs.

* Personal Computer / Hardware
Right now I'm mosting using a Thinkpad T430 running Qubes OS with an i7-3840QM and 16GB of RAM that I corebooted myself. Last year I was daily-driving a [[https://libreboot.org/][librebooted]] ThinkPad T400, [[https://vid.puffyan.us/watch?v=Fs4GjDiOie8][specially modded]] with a quad core CPU. It runs Debian 12, and I'm guessing the only non-free software running on it is the trackpad firmware. I also have a ThinkPad P15s that dual boots Arch Linux and Windows 10. I generally use this machine a lot less because the keyboard and mouse are broken and I haven't bothered to get it fixed for the past year and a half. I like listening to music while I study or run, for that I use an ipod nano 2g with [[https://www.rockbox.org/][RockBox]], a free firmware replacement for music players that can also play Doom. Recently I've been loading a lot of books, manga, and even school materials onto my Kobo Libra 2 (which I keep offline). It's has been really nice on my eyes, maybe I'll get around to trying the [[https://www.pine64.org/pinenote/][PineNote]] for it's full consumer release.

* Cell Phone
I own an unlocked Pixel 7 running [[https://grapheneos.org][GrapheneOS]]. The Pixel series of phones are probably the best to run either a default AOSP experience or custom ROMs to deliver the premium degoogled android experience, which is ironically on Google's very own hardware. The software experience is the best that I could ask for though the form factor and screen size are a little big for my liking. Regardless, the stuff that the GrapheneOS team are doing is very impressive, if you're interested in using it make sure you purchase a compatable pixel device that is *unlocked*. [[/posts/adb_vanadium/][I also removed the browser from my phone using adb]] so that it is less distracting, but if you wish to do the same proceed at your own risk.

* Software
In terms of software, Emacs is a huge part of my productivity environment, and acts as my IDE, document writer, RSS feed, and I even made this site with it! I of course use evil mode due to the extramarital affair I have with Vim. I've used a couple of window managers including dwm and awesomewm, but I'm sure I'll get to using wayland one of these years. My shell is bash, never really bothered to use anything else really. For browsing I use Librewolf, a fork of Firefox with more privacy protections by default. 
