#+TITLE: Mapping Caps Lock to Esc and CTRL in Xorg
#+CATEGORY: Tutorial
The Emacs editor was designed in the 1980's in the era of old unix keyboards when the control key was next to the "A" key, a lot of functionality in Emacs was designed around CTRL keybindings. While there are hobbyist keyboards for that kind of layout, no real usable laptop these days would oblige without some serious changes. This has had the undesireable outcome of exasterbating repetitive strain injury (RSI) in some pretty famous programmers[[cite:famous_progr_repet_strain_injur]].


Now I'm regularly using evil mode to edit files with Emacs so it shouldn't be as big of an issue for someone like myself, however, I'm not interesting in running the risk having RSI on my pinky by the time I'm 50 because I used ~C-x C-f~ too many times. One solution would be switching to Doom or Spacemacs or otherwise changing my ~init.el~ file in emacs to use the control key much less. Many people use xmonad to change keyboard layouts as well. However, I feel like those solutions are a bit overkill, and I found a decent solution for my case without having to change very much about my system using xkb, which is how keyboard codes are handled in Xorg[[cite:unknownil_x_archw]]. 

* The Guide

The main inspiration of this tutorial comes from Ben Davis on github who outlined a very similar guide but for making Capslock into an Esc and Mod4 key[[cite:mapping_caps_lock_esc_super_mod4_github]].

** Requirements 
This guide assumes you're using GNU/Linux or a BSD distrobution that uses xkb for the keyboard layout. You will also need ~setxkbmap~ installed, though that should come with Xorg by default. I'm using dwm as my window manager though everything outlined here should work on any desktop environment (I hope, please correct me if I'm wrong), even if other DE's have different ways of updating keyboard layout options as is outlined in Ben Davis's guide[[cite:mapping_caps_lock_esc_super_mod4_github]].
** Creating user defined layout in xkb
First we define our custom layout by creating the file ~/usr/share/X11/xkb/symbols/custom_opts~. We put in the following to map Capslock to escape, and make it act as a control key when in combination with other keys.

#+BEGIN_SRC
// Make Caps another escape key when pressed once while simultaneously having functionality of control. 
xkb_symbols "ctrl_esc" {
    key <CAPS> { [ Escape ] };
    modifier_map Control { <CAPS>};
};
#+END_SRC

Now edit ~/usr/share/X11/xkb/rules/evdev~ and add a new line in the ~! option = symbols~ section:

#+BEGIN_SRC
custom:ctrl_esc = +custom_opts(ctrl_esc)
#+END_SRC

Edit ~/usr/share/X11/xkb/rules/evdev.lst~ and add a new line the ~! option~ section:

#+BEGIN_SRC
custom:ctrl_esc  Make Caps Lock an additional ESC and CTRL 
#+END_SRC

** Updating Keyboard layout
We can apply these changes from the command line using ~setxkbmap~. ~setxkbmap~ specifies the keyboard layout to be used based on the specified based on the components in ~/usr/share/X11/xkb/~ that we were just changing. Run the command with the ~-option~ flag and the name of our custom layout rules:

#+BEGIN_SRC sh
$ setxkbmap -option "custom:ctrl_esc"
#+END_SRC

To run this automatically at the start of your xorg session, go into your ~.xinitrc~ file (either in your home directory or ~/etc/X11/xnit/.xinitrc~) and add the above command. Now when your Xorg session is restarted this keymapping will begin working. 

#+BIBLIOGRAPHY: references unsrt limit:t option:-nobibsource
#+INCLUDE: "~/Website/content/base.org::*Footer" :only-contents t
bibliographystyle:unsrt
bibliography:references.bib
* Bibliography :noexport:

* Abstract :noexport:
Guide on switching keymaps using xkb in Xorg 

